// <auto-generated />
namespace Cben.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbUpdate_170420 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbUpdate_170420));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191847279_DbUpdate_170420"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
